#pragma once

#define in_attack ( 1 << 0 )
#define in_jump ( 1 << 1 )
#define in_duck ( 1 << 2 )
#define in_forward ( 1 << 3 )
#define in_back ( 1 << 4 )
#define in_use ( 1 << 5 )
#define in_cancel ( 1 << 6 )
#define in_left ( 1 << 7 )
#define in_right ( 1 << 8 )
#define in_move_left ( 1 << 9 )
#define in_move_right ( 1 << 10 )
#define in_attack2 ( 1 << 11 )
#define in_run ( 1 << 12 )
#define in_reload ( 1 << 13 )
#define in_alt1 ( 1 << 14 )
#define in_alt2 ( 1 << 15 )
#define in_score ( 1 << 16 )
#define in_speed ( 1 << 17 )
#define in_walk ( 1 << 18 )
#define in_zoom ( 1 << 19 )
#define in_weapon1 ( 1 << 20 )
#define in_weapon2 ( 1 << 21 )
#define in_bull_rush ( 1 << 22 )
#define in_grenade1 ( 1 << 23 )
#define in_grenade2 ( 1 << 24 )
#define in_attack3 ( 1 << 25 )